"""
Monitoring Demo: Model training, drift detection, metrics, and alerts

This script:
1. Loads reference/current regression data generated by generate_synthetic_data.py
2. Trains a regression model on the reference data
3. Runs multiple drift detectors (KS, PSI, ML-based)
4. Computes performance metrics and triggers alerts via AlertManager
"""

from pathlib import Path
import pandas as pd
from sklearn.ensemble import RandomForestRegressor

from ml_monitor import ModelMonitor
from ml_monitor.drift_detection import StatisticalDriftDetector, MLBasedDriftDetector
from ml_monitor.monitoring.alerts import AlertManager, AlertThresholds


DATA_DIR = Path("data")
REF_FEATURES_PATH = DATA_DIR / "reference_data.csv"
REF_TARGETS_PATH = DATA_DIR / "reference_targets.csv"
CURR_FEATURES_PATH = DATA_DIR / "current_data.csv"
CURR_TARGETS_PATH = DATA_DIR / "current_targets.csv"


def load_data() -> tuple[pd.DataFrame, pd.Series, pd.DataFrame, pd.Series]:
    """Load reference/current feature and target data from CSV files."""
    missing = [
        p
        for p in [
            REF_FEATURES_PATH,
            REF_TARGETS_PATH,
            CURR_FEATURES_PATH,
            CURR_TARGETS_PATH,
        ]
        if not p.exists()
    ]
    if missing:
        missing_str = ", ".join(str(p) for p in missing)
        raise FileNotFoundError(
            f"Missing data files: {missing_str}. "
            "Run `python examples/generate_synthetic_data.py` first."
        )

    reference_data = pd.read_csv(REF_FEATURES_PATH)
    reference_targets = pd.read_csv(REF_TARGETS_PATH)["target"]

    current_data = pd.read_csv(CURR_FEATURES_PATH)
    current_targets = pd.read_csv(CURR_TARGETS_PATH)["target"]

    return reference_data, reference_targets, current_data, current_targets


def main() -> None:
    """Run monitoring demo using saved synthetic data."""
    print("Loading synthetic regression data from disk...")
    reference_data, reference_targets, current_data, current_targets = load_data()

    print(f"Reference shape: {reference_data.shape}")
    print(f"Current shape:   {current_data.shape}")

    # Train regression model
    print("\nTraining regression model...")
    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(reference_data, reference_targets)
    print("Model trained.")

    # Configure drift detectors
    detectors = {
        "KS Test": StatisticalDriftDetector(threshold=0.05, method="ks_test"),
        "PSI": StatisticalDriftDetector(threshold=0.05, method="psi"),
        "ML-Based": MLBasedDriftDetector(threshold=0.6),
    }

    # Configure alerts (all logic lives in AlertManager)
    thresholds = AlertThresholds(prediction_mean_threshold=1.5)
    alert_manager = AlertManager(thresholds=thresholds)

    print("\n" + "=" * 60)
    print("MONITORING DEMO: MODEL + METRICS + ALERTS")
    print("=" * 60)

    for name, detector in detectors.items():
        print(f"\n--- {name} ---")

        monitor = ModelMonitor(
            model=model,
            drift_detector=detector,
            alert_manager=alert_manager,
        )

        monitor.set_reference(reference_data, reference_targets)
        results = monitor.monitor(current_data, current_targets)

        drift = results["drift"]
        print(f"Drift Detected: {drift['drift_detected']}")
        print(f"Drift Score:    {drift['drift_score']:.4f}")

        if "feature_results" in drift:
            num_with_drift = sum(
                1 for r in drift["feature_results"].values() if r.get("drift_detected")
            )
            print(f"Features with drift: {num_with_drift}")

        print("\nPerformance Metrics:")
        for metric, value in results.get("performance", {}).items():
            print(f"  {metric}: {value:.4f}")

        print("\nAlerts:")
        alerts = results.get("alerts", [])
        print(f"  Count: {len(alerts)}")
        for alert in alerts:
            print(f"  [{alert['level']}] {alert['type']}: {alert['message']}")

    print("\n" + "=" * 60)


if __name__ == "__main__":
    main()
